services:
  # Backend API service
  - type: web
    name: document-disk-backend
    env: python
    region: oregon # Choose your preferred region
    plan: free # Adjust as needed
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false # This will be manually set
      - key: DB_NAME
        value: document_disk_production
      - key: SECRET_KEY
        generateValue: true # Automatically generate a secure random value
      - key: PORT
        value: 8000

  # Frontend static site
  - type: web
    name: document-disk-frontend
    env: static
    buildCommand: cd frontend && yarn install && yarn build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://document-disk-backend.onrender.com
    routes:
      - type: rewrite
        source: /api/*
        destination: https://document-disk-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html